---
- name: Create pods using deployment 
  hosts: all
  become: true
  tasks: 
  - name: copy files
    copy: src=/home/renga5/workspace/task/nginx.yaml dest=/home/renga5/
  - name: command
    command: sudo kubectl create -f /home/renga5/nginx.yaml
  - name: git
    git: 
       repo: https://github.com/rengaprakashs/kubernetespipeline.git
       dest: /home/renga2
