--- 
- 
  hosts: all
  name: "Create pods using deployment"
  tasks: 
    - 
      community.kubernetes.k8s: 
        src: nginx.yaml
        state: present
      name: "create a deployment"
  user: renga5
