---
- name: Create pods using deployment 
  hosts: all
  #become: true
  user: renga5
 
  tasks: 
  - name: create a deployment
    command: "sudo kubectl create -f /home/renga5/workspace/task/nginx.yaml"
