---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: mynginx1
spec:
  ports:
  - nodePort: 32224
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
